name: Waka Readme

on:
  schedule:
    # 00:00 IST (18:30 UTC)
    - cron: "30 18 * * *"
  workflow_dispatch:

# REQUIRED so the action can push changes
permissions:
  contents: write

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest

    steps:
      - name: Update README with WakaTime stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # -------- Display Settings --------
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_UPDATED_DATE: "True"

          # -------- Other Config --------
          COMMIT_BY_ME: "False"
          LOCALE: "en"
          SECTION_NAME: "waka-readme"
          COMMIT_MESSAGE: "Updated with Dev Metrics"
          COMMIT_USERNAME: "github-actions[bot]"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          IGNORED_REPOS: ""
          BADGE_STYLE: "for-the-badge"
          SYMBOL_VERSION: "1"
